export const GET_ARTICLES = 'GET_ARTICLES';
export const SAGA_GET_ARTICLES = 'SAGA_GET_ARTICLES';

export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const SAGA_REMOVE_ARTICLE = 'SAGA_REMOVE_ARTICLE';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const SAGA_ADD_ARTICLE = 'SAGA_ADD_ARTICLE';
