export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SAGA_GET_CATEGORIES = 'SAGA_GET_CATEGORIES';

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SAGA_REMOVE_CATEGORY = 'SAGA_REMOVE_CATEGORY';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SAGA_ADD_CATEGORY = 'SAGA_ADD_CATEGORY';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SAGA_SET_CATEGORY = 'SAGA_SET_CATEGORY';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const SAGA_EDIT_CATEGORY = 'SAGA_EDIT_CATEGORY';
